version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: vedora_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vedora_db
    ports:
      - '5432:5432'
    volumes:
      - vedora_pgdata:/var/lib/postgresql/data

volumes:
  vedora_pgdata:
