export enum NotificationKey {
  // Auth & Account
  AUTH_PASSWORD_RESET_DONE = 'AUTH_PASSWORD_RESET_DONE',
  ACCOUNT_PASSWORD_CHANGED = 'ACCOUNT_PASSWORD_CHANGED',
  ACCOUNT_CONTACT_CHANGED = 'ACCOUNT_CONTACT_CHANGED',
  ACCOUNT_STATUS_CHANGED = 'ACCOUNT_STATUS_CHANGED',

  // Joining & Team
  PARTNER_WELCOME = 'PARTNER_WELCOME',
  TEAM_DIRECT_JOINED = 'TEAM_DIRECT_JOINED',
  TEAM_DOWNLINE_JOINED = 'TEAM_DOWNLINE_JOINED',
  TEAM_SLOTS_ALMOST_FULL = 'TEAM_SLOTS_ALMOST_FULL',
  TEAM_SLOTS_FULL = 'TEAM_SLOTS_FULL',

  // Orders & Payments
  ORDER_AWAITING_PAYMENT = 'ORDER_AWAITING_PAYMENT',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  CASH_ORDER_RECORDED = 'CASH_ORDER_RECORDED',
  ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED',

  // Commission Income
  COMMISSION_CREDITED = 'COMMISSION_CREDITED',
  COMMISSION_MISSED_INACTIVE = 'COMMISSION_MISSED_INACTIVE',

  // Withdrawals & Bank
  WITHDRAWAL_REQUESTED = 'WITHDRAWAL_REQUESTED',
  WITHDRAWAL_APPROVED = 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED = 'WITHDRAWAL_REJECTED',
  WITHDRAWAL_PAID = 'WITHDRAWAL_PAID',
  BANK_ADDED = 'BANK_ADDED',
  BANK_PRIMARY_CHANGED = 'BANK_PRIMARY_CHANGED',
  BANK_VERIFIED = 'BANK_VERIFIED',

  // Admin Notifications & Broadcasts
  ADMIN_WITHDRAWAL_PENDING = 'ADMIN_WITHDRAWAL_PENDING',
  ADMIN_BANK_TO_VERIFY = 'ADMIN_BANK_TO_VERIFY',
  PRODUCT_LAUNCHED = 'PRODUCT_LAUNCHED',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
}
